// Generated by CoffeeScript 1.9.3
(function() {
  var API_LIVE_URL, API_SANDBOX_URL, API_VERSION, PayPal, _, querystring, request, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  request = require('request');

  querystring = require('querystring');

  _ = require('underscore');

  util = require('util');

  API_LIVE_URL = 'https://api-3t.paypal.com/nvp';

  API_SANDBOX_URL = 'https://api-3t.sandbox.paypal.com/nvp';

  API_VERSION = 94;

  PayPal = (function() {
    function PayPal(options) {
      this.call = bind(this.call, this);
      this.apiUrl = options.live ? API_LIVE_URL : API_SANDBOX_URL;
      this.username = options.username;
      this.password = options.password;
      this.signature = options.signature;
    }

    PayPal.prototype.call = function(method, parameters, callback) {
      var args, k, processResponse, v;
      processResponse = function(text) {
        var data, extractValue, i, ids, k, key, len, p, params, ref, response, rx;
        data = querystring.decode(text);
        if (data == null) {
          return typeof callback === "function" ? callback('invalid server response') : void 0;
        }
        response = {};
        extractValue = function(key, value) {
          var date;
          if (key === 'TRANSACTIONID') {
            return value;
          }
          if (!isNaN(value)) {
            value = parseFloat(value);
          }
          if (key === 'TIMESTAMP' || /.+DATE$/.test(key)) {
            date = new Date(value);
            if (date && !isNaN(date.getYear())) {
              value = date;
            }
          }
          return value;
        };
        ref = ((function() {
          var results;
          results = [];
          for (k in data) {
            results.push(k);
          }
          return results;
        })()).filter(function(k) {
          return /^[A-Z]+$/.test(k);
        });
        for (i = 0, len = ref.length; i < len; i++) {
          key = ref[i];
          response[key] = extractValue(key, data[key]);
        }
        rx = /^L_([A-Z]+)(\d+)$/;
        params = (((function() {
          var results;
          results = [];
          for (k in data) {
            results.push(k);
          }
          return results;
        })()).map(function(key) {
          var parts;
          if (!rx.test(key)) {
            return;
          }
          parts = rx.exec(key);
          if (parts) {
            return [parts[1], parseInt(parts[2]), key];
          } else {
            return null;
          }
        })).filter(function(p) {
          return p != null;
        });
        ids = (function() {
          var j, len1, results;
          results = [];
          for (j = 0, len1 = params.length; j < len1; j++) {
            p = params[j];
            results.push(p[1]);
          }
          return results;
        })();
        ids = _.uniq(_.flatten(ids));
        response["objects"] = ids.map(function(id) {
          var j, len1, obj, param;
          obj = {};
          for (j = 0, len1 = params.length; j < len1; j++) {
            param = params[j];
            if (id === param[1]) {
              obj[param[0]] = extractValue(param[0], data[param[2]]);
            }
          }
          return obj;
        });
        return response;
      };
      args = {
        USER: this.username,
        PWD: this.password,
        SIGNATURE: this.signature,
        METHOD: method,
        VERSION: API_VERSION
      };
      for (k in parameters) {
        v = parameters[k];
        args[k] = v;
      }
      return request.post({
        url: this.apiUrl,
        body: querystring.encode(args)
      }, function(error, response, body) {
        if (error) {
          return typeof callback === "function" ? callback(error) : void 0;
        }
        return typeof callback === "function" ? callback(null, processResponse(body)) : void 0;
      });
    };

    return PayPal;

  })();

  module.exports = PayPal;

}).call(this);
